### ISSUE TITLE
Remove upper bound on python_requires

### ISSUE THREAD

**Issue by matthewfeickert** [gradhep/relaxed#40]
At the moment the project has an upper bound on `python_requires`

https://github.com/gradhep/relaxed/blob/8842107fe902667268ff34a7392b0192ec18102c/setup.cfg#L41

I would highly recommend removing this for the reasons summarized in Henry's [detailed blog post on the subject](https://iscinumpy.dev/post/bound-version-constraints/) unless you know for certain that there is some behavior in CPython 3.10 that breaks your code.

**Comment by phinate** [comment]
Thanks for flagging this @matthewfeickert! Would not have thought this could cause problems downstream, so I appreciate you hunting down my reasoning :)
